apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\PATH\kompose-1.22.0.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jvb
  name: jvb
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 30300
      protocol: UDP
      targetPort: 30300
      nodePort: 30300
  selector:
    io.kompose.service: jvb
status:
  loadBalancer: {}
