apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: jvb
  name: jvb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jvb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-jitsi-meet-default: "true"
        io.kompose.service: jvb
    spec:
      containers:
        - env:
#            - name: DOCKER_HOST_ADDRESS
#              value: 192.168.1.1
            - name: JVB_AUTH_PASSWORD
              value: "12345"
            - name: JVB_PORT
              value: "30300"
            - name: PUBLIC_URL
              value: https://meet-local.lybl.com
            - name: SENTRY_DSN
              value: '"0"'
            - name: TZ
              value: UTC
            - name: XMPP_SERVER
              value: prosody
          image: jitsi/jvb:stable-8922
          name: jvb
          ports:
            - containerPort: 30300
              protocol: UDP
            - containerPort: 30301
              protocol: TCP
            - containerPort: 9090
              hostPort: 9090
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
